UPDATE db.answer SET title = 'Première réponse', isActive = 1 WHERE answer_id = 1;
UPDATE db.answer SET title = 'Deuxième réponse', isActive = 1 WHERE answer_id = 2;
UPDATE db.answer SET title = 'Troisième réponse', isActive = 1 WHERE answer_id = 3;
UPDATE db.answer SET title = 'Quatrième réponse', isActive = 1 WHERE answer_id = 4;
UPDATE db.answer_question SET question_id = 2, answer_id = 1, position = 1, isValid = 1 WHERE answer_question_id = 1;
UPDATE db.answer_question SET question_id = 2, answer_id = 2, position = 2, isValid = 0 WHERE answer_question_id = 2;
UPDATE db.answer_question SET question_id = 2, answer_id = 3, position = 3, isValid = 0 WHERE answer_question_id = 3;
UPDATE db.answer_question SET question_id = 2, answer_id = 4, position = 4, isValid = 0 WHERE answer_question_id = 4;
UPDATE db.answer_question SET question_id = 3, answer_id = 1, position = 1, isValid = 0 WHERE answer_question_id = 5;
UPDATE db.answer_question SET question_id = 3, answer_id = 2, position = 2, isValid = 0 WHERE answer_question_id = 6;
UPDATE db.answer_question SET question_id = 3, answer_id = 3, position = 3, isValid = 0 WHERE answer_question_id = 7;
UPDATE db.answer_question SET question_id = 3, answer_id = 4, position = 4, isValid = 1 WHERE answer_question_id = 8;
UPDATE db.form SET title = 'kdjsfhkjshfkjh', isActive = 1 WHERE form_id = 81;
UPDATE db.form_question SET form_id = 81, question_id = 2, position = 1 WHERE form_question_id = 56;
UPDATE db.form_question SET form_id = 81, question_id = 3, position = 2 WHERE form_question_id = 57;
/*UPDATE db.form_subject SET  WHERE form_id = 81 AND subject_id = 1;*/
UPDATE db.question SET subject_id = 1, title = 'Question 1', isActive = 1 WHERE question_id = 2;
UPDATE db.question SET subject_id = 1, title = 'Question 2', isActive = 1 WHERE question_id = 3;
UPDATE db.role SET name = 'ROLE_ADMIN' WHERE id = 1;
UPDATE db.role SET name = 'ROLE_USER' WHERE id = 2;
UPDATE db.role SET name = 'ROLE_USER' WHERE id = 3;
UPDATE db.subject SET title = 'Java' WHERE subject_id = 1;
UPDATE db.subject SET title = 'C++' WHERE subject_id = 2;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-13T16:09:38.036', date = '2019-06-13T16:09:38.036' WHERE track_id = 13;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-13T16:21:22.283', date = '2019-06-13T16:21:22.283' WHERE track_id = 14;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T00:35:08.851', date = '2019-06-14T00:35:08.851' WHERE track_id = 15;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T00:54:36.513', date = '2019-06-14T00:54:36.513' WHERE track_id = 16;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T00:56:50.883', date = '2019-06-14T00:56:50.883' WHERE track_id = 17;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T01:10:52.838', date = '2019-06-14T01:10:52.837' WHERE track_id = 18;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T01:26:28.981', date = '2019-06-14T01:26:28.981' WHERE track_id = 19;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T01:42:28.996', date = '2019-06-14T01:42:28.996' WHERE track_id = 20;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T01:56:54.193', date = '2019-06-14T01:56:54.193' WHERE track_id = 21;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T02:00:10.538', date = '2019-06-14T02:00:10.538' WHERE track_id = 22;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T02:52:55.331', date = '2019-06-14T02:52:55.331' WHERE track_id = 23;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T02:52:55.487', date = '2019-06-14T02:52:55.487' WHERE track_id = 24;
UPDATE db.track SET form_id = 81, user_id = 18, score = 3, duration = '2019-06-14T03:06:42.815', date = '2019-06-14T03:06:42.815' WHERE track_id = 25;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T03:08:40.556', date = '2019-06-14T03:08:40.556' WHERE track_id = 26;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T03:09:59.363', date = '2019-06-14T03:09:59.363' WHERE track_id = 27;
UPDATE db.track SET form_id = 81, user_id = 18, score = 0, duration = '2019-06-14T03:10:30.455', date = '2019-06-14T03:10:30.455' WHERE track_id = 28;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T03:20:50.100', date = '2019-06-14T03:20:50.100' WHERE track_id = 29;
UPDATE db.track SET form_id = 81, user_id = 18, score = 1, duration = '2019-06-14T03:21:00.238', date = '2019-06-14T03:21:00.238' WHERE track_id = 30;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T03:29:33.168', date = '2019-06-14T03:29:33.168' WHERE track_id = 31;
UPDATE db.track SET form_id = 81, user_id = 18, score = 2, duration = '2019-06-14T03:33:05.959', date = '2019-06-14T03:33:05.959' WHERE track_id = 32;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 2;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 3;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 4;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 5;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 6;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 7;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 8;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 9;
UPDATE db.track_question SET track_id = 13, question_id = 2, choicePosition = 0 WHERE track_question_id = 10;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 11;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 12;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 13;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 14;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 15;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 16;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 17;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 18;
UPDATE db.track_question SET track_id = 14, question_id = 2, choicePosition = 0 WHERE track_question_id = 19;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 20;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 21;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 22;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 23;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 24;
UPDATE db.track_question SET track_id = 15, question_id = 3, choicePosition = 0 WHERE track_question_id = 25;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 26;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 27;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 28;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 29;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 30;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 31;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 32;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 33;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 34;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 35;
UPDATE db.track_question SET track_id = 15, question_id = 2, choicePosition = 0 WHERE track_question_id = 36;
UPDATE db.track_question SET track_id = 16, question_id = 2, choicePosition = 0 WHERE track_question_id = 37;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 38;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 39;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 40;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 41;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 42;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 43;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 44;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 45;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 46;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 47;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 48;
UPDATE db.track_question SET track_id = 17, question_id = 2, choicePosition = 0 WHERE track_question_id = 49;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 50;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 51;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 52;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 53;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 54;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 55;
UPDATE db.track_question SET track_id = 18, question_id = 2, choicePosition = 0 WHERE track_question_id = 56;
UPDATE db.track_question SET track_id = 19, question_id = 2, choicePosition = 0 WHERE track_question_id = 57;
UPDATE db.track_question SET track_id = 19, question_id = 2, choicePosition = 0 WHERE track_question_id = 58;
UPDATE db.track_question SET track_id = 19, question_id = 2, choicePosition = 2 WHERE track_question_id = 59;
UPDATE db.track_question SET track_id = 19, question_id = 3, choicePosition = 1 WHERE track_question_id = 60;
UPDATE db.track_question SET track_id = 20, question_id = 2, choicePosition = 1 WHERE track_question_id = 61;
UPDATE db.track_question SET track_id = 20, question_id = 3, choicePosition = 4 WHERE track_question_id = 62;
UPDATE db.track_question SET track_id = 20, question_id = 3, choicePosition = 3 WHERE track_question_id = 63;
UPDATE db.track_question SET track_id = 21, question_id = 2, choicePosition = 2 WHERE track_question_id = 64;
UPDATE db.track_question SET track_id = 22, question_id = 2, choicePosition = 1 WHERE track_question_id = 65;
UPDATE db.track_question SET track_id = 22, question_id = 3, choicePosition = 4 WHERE track_question_id = 66;
UPDATE db.track_question SET track_id = 22, question_id = 3, choicePosition = 3 WHERE track_question_id = 67;
UPDATE db.track_question SET track_id = 24, question_id = 2, choicePosition = 3 WHERE track_question_id = 68;
UPDATE db.track_question SET track_id = 24, question_id = 3, choicePosition = 3 WHERE track_question_id = 69;
UPDATE db.track_question SET track_id = 24, question_id = 3, choicePosition = 3 WHERE track_question_id = 70;
UPDATE db.track_question SET track_id = 24, question_id = 3, choicePosition = 4 WHERE track_question_id = 71;
UPDATE db.track_question SET track_id = 24, question_id = 3, choicePosition = 4 WHERE track_question_id = 72;
UPDATE db.track_question SET track_id = 24, question_id = 3, choicePosition = 3 WHERE track_question_id = 73;
UPDATE db.track_question SET track_id = 25, question_id = 2, choicePosition = 1 WHERE track_question_id = 74;
UPDATE db.track_question SET track_id = 25, question_id = 3, choicePosition = 4 WHERE track_question_id = 75;
UPDATE db.track_question SET track_id = 25, question_id = 3, choicePosition = 4 WHERE track_question_id = 76;
UPDATE db.track_question SET track_id = 26, question_id = 2, choicePosition = 4 WHERE track_question_id = 77;
UPDATE db.track_question SET track_id = 26, question_id = 3, choicePosition = 1 WHERE track_question_id = 78;
UPDATE db.track_question SET track_id = 27, question_id = 2, choicePosition = 1 WHERE track_question_id = 79;
UPDATE db.track_question SET track_id = 27, question_id = 3, choicePosition = 4 WHERE track_question_id = 80;
UPDATE db.track_question SET track_id = 28, question_id = 2, choicePosition = 3 WHERE track_question_id = 81;
UPDATE db.track_question SET track_id = 28, question_id = 3, choicePosition = 2 WHERE track_question_id = 82;
UPDATE db.track_question SET track_id = 29, question_id = 2, choicePosition = 1 WHERE track_question_id = 83;
UPDATE db.track_question SET track_id = 29, question_id = 3, choicePosition = 4 WHERE track_question_id = 84;
UPDATE db.track_question SET track_id = 30, question_id = 2, choicePosition = 2 WHERE track_question_id = 85;
UPDATE db.track_question SET track_id = 30, question_id = 3, choicePosition = 4 WHERE track_question_id = 86;
UPDATE db.track_question SET track_id = 31, question_id = 2, choicePosition = 1 WHERE track_question_id = 87;
UPDATE db.track_question SET track_id = 31, question_id = 3, choicePosition = 4 WHERE track_question_id = 88;
UPDATE db.track_question SET track_id = 32, question_id = 2, choicePosition = 1 WHERE track_question_id = 89;
UPDATE db.track_question SET track_id = 32, question_id = 3, choicePosition = 4 WHERE track_question_id = 90;
UPDATE db.user SET username = 'luc_brizard', password = '$2a$11$/4nviwT0cVUIDNJgeFmE5eb5mINUGtGBKTOelLzuJKi5wQcXQrKEC', valid = 1, firstName = 'luc', secondName = 'brizard', mail = 'luc@gmail.com', company = 'fsa', phone = '0987654321', creationdate = '2019-05-26 12:17:50' WHERE id = 5;
UPDATE db.user SET username = 'cbrizard', password = '$2a$11$wif42eGZWdbqnej7h1ERveZa91j6Q3t8x2QpkAiaEfHaPAzooPn/u', valid = 1, firstName = 'clementine', secondName = 'Brizard', mail = 'clementbrizard53@gmail.com', company = 'UTC', phone = '0770976800', creationdate = '2019-05-26 17:58:41' WHERE id = 13;
UPDATE db.user SET username = 'anne_laure_briz', password = '$2a$11$JvU6gs7KM0c3GoJxgdfXd.GxXdf/PjSXdYj.yDy2RCadADT6ibXlq', valid = 1, firstName = 'anne-laure', secondName = 'Brizard', mail = 'alb@gmail.com', company = 'PSL', phone = '0987654322', creationdate = '2019-05-26 18:09:32' WHERE id = 14;
UPDATE db.user SET username = 'jean-brzard', password = '$2a$11$D1sFpoV5c5/7Cx81VKASzuG4paerokbR43yaphpgTXEqoa9GOj7hm', valid = 1, firstName = 'jean', secondName = 'Brizard', mail = 'jean@gmail.com', company = 'Immac', phone = '0987654321', creationdate = '2019-05-26 18:15:38' WHERE id = 15;
UPDATE db.user SET username = 'marie_briz', password = '$2a$11$X24H5Ssq/4tR.7wrfPnzEe4hTuSdwzRGG12KFmBGjve.Fdhg02YlS', valid = 1, firstName = 'marie', secondName = 'brizard', mail = 'marie@gmail.com', company = 'FSA', phone = '0608315289', creationdate = '2019-05-27 02:11:49' WHERE id = 16;
UPDATE db.user SET username = 'ninon_lize', password = '$2a$11$OB7vtSX8CvgvjlrnmGCU7eAmc2Tfax9uhPrD.JoWPKZ5/38n7X0nS', valid = 1, firstName = 'ninon', secondName = 'lize', mail = 'ninon@gmail.com', company = 'UTC', phone = '0987654321', creationdate = '2019-05-27 02:15:00' WHERE id = 17;
UPDATE db.user SET username = 'clement_brizard_53', password = '$2a$11$bU4wGxJ7GJ525GAlr4YzDelZxbKy4KuxDQwG2Oz.VZUWHLjEwjSdq', valid = 1, firstName = 'clement', secondName = 'brizard', mail = 'clementbrizard@gmail.com', company = 'UTC', phone = '0770976800', creationdate = '2019-06-03 08:56:52' WHERE id = 18;
/*UPDATE db.user_role SET  WHERE user_id = 5 AND role_id = 1;
UPDATE db.user_role SET  WHERE user_id = 5 AND role_id = 2;
UPDATE db.user_role SET  WHERE user_id = 18 AND role_id = 2;*/